StoreFront.UI.MVC/Controllers/FiltersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using StoreFront.DATA.EF;

namespace StoreFront.UI.MVC.Controllers
{
    public class FiltersController : Controller
    {
        private StorefrontEntities db = new StorefrontEntities();

        // GET: Filters
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Category).Include(p => p.StockStatu);
            return View(products.ToList());
        }

        public ActionResult ProductQS(string searchFilter)//Parameter name matches the textbox name
        {
            #region Optional Search Filter

            //Check if the searchFilter string was provided/has content
            if (String.IsNullOrEmpty(searchFilter))
            {
                //If optional search isn't used, return all records
                var products = db.Products;
                return View(products.ToList());
            }
            else
            {
                //If the optional search is used, then filter the results by those
                //criteria (compare to first or last name and ignore casing concerns)

                //v1 LINQ Method/Lambda Syntax
                string searchLowCase = searchFilter.ToLower();

                List<Product> searchResults = db.Products.Where(
                    p => p.ProductName.ToLower().Contains(searchLowCase)).ToList();

                return View(searchResults);

            }

            #endregion

        }

        public ActionResult ProductPaging(string searchFilter, int page = 1)
        {
            int pageSize = 5;

            ViewBag.SearchFilter = new SelectList(db.Products.Select(x => x.Category.CategoryName).Distinct());

            if (String.IsNullOrEmpty(searchFilter))
            {
                var products = db.Products.OrderBy(p => p.ProductName).ToList();
                return View(products.ToPagedList(page, pageSize));
            }
            else
            {
                string searchLowCase = searchFilter.ToLower();

                List<Product> searchResults = db.Products.Where(
                    p => p.ProductName.ToLower().Contains(searchLowCase)).ToList();
                return View(searchResults);
            }
        }
    }
}

StoreFront.UI.MVC/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StoreFront.UI.MVC.Models;
using StoreFront.UI.MVC.Controllers;

namespace StoreFront.UI.MVC.Controllers
{
    public class ShoppingCartController : Controller
    {
        // GET: ShoppingCart -- Generate this View with the List template for CartItemViewModel objects (No data context)
        public ActionResult Index()
        {
            //Pull session cart into a local variable, which we can then pass to the View
            var shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];

            if (shoppingCart == null || shoppingCart.Count == 0)
            {
                //User either hasn't put anything in the cart, removed all cart items, or session expired...
                //Set the cart to an empty cart object (we can still send that to the View, UNLIKE a NULL value)
                shoppingCart = new Dictionary<int, CartItemViewModel>();

                //Create a message informing them about the empty cart
                ViewBag.Message = "There are no items in your cart.";
            }
            else
            {
                ViewBag.Message = null;//Explicitly clears out that ViewBag variable
            }

            return View(shoppingCart);
        }


        public ActionResult RemoveFromCart(int id)
        {
            Dictionary<int, CartItemViewModel> shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];
            shoppingCart.Remove(id);
            if (shoppingCart.Count == 0)
            {
                Session["cart"] = null;
            }
            return RedirectToAction("Index");
        }

        public ActionResult UpdateCart(int productID, int qty)
        {
            if (qty == 0)
            {
                RemoveFromCart(productID);
                return RedirectToAction("Index");
            }
            Dictionary<int, CartItemViewModel> shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];
            shoppingCart[productID].Qty = qty;
            Session["cart"] = shoppingCart;
            if (shoppingCart.Count == 0)
            {
                ViewBag.Message = "There are no products in your cart";
            }
            return RedirectToAction("Index");
        }

    }
}

StoreFront.UI.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title | StarFront</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />

    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/south-street/jquery-ui.css">
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    @Styles.Render("~/Content/css")
    <link href="~/Content/css/styles.css" rel="stylesheet" id="theme"/>

   
    

    @RenderSection("htmlHead", required: false)
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href=@Url.Action("Index", "Home")>StarFront</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href=@Url.Action("Index", "Home")>Home</a></li>
                    <li class="nav-item"><a class="nav-link" href=@Url.Action("About", "Home")>About</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href=@Url.Action("ProductPaging", "Filters")>All Products</a></li>
                            <li><hr class="dropdown-divider" /></li>
                            <li><a class="dropdown-item" href=@Url.Action("ProductPaging", "Filters")>Underground Market</a></li>
                            <li><a class="dropdown-item" href=@Url.Action("ProductPaging", "Filters")>Star Wars Merchandise</a></li>
                        </ul>
                    </li>
                    <li class="nav-item"><a class="nav-link" href=@Url.Action("Contact", "Home")>Contact</a></li>
                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li class="nav-item"><a class="nav-link" href=@Url.Action("RolesAdmin", "Index", "RolesAdmin")>Admin Roles</a></li>
                        <li class="nav-item"><a class="nav-link" href=@Url.Action("UsersAdmin", "Index", "UsersAdmin")>Users</a></li>
                    }
                </ul>
                @{ Dictionary<int, StoreFront.UI.MVC.Models.CartItemViewModel> products = (Dictionary<int, StoreFront.UI.MVC.Models.CartItemViewModel>)Session["cart"];}

                @if (Session["cart"] != null && ((Dictionary<int, StoreFront.UI.MVC.Models.CartItemViewModel>)Session["cart"]).Count > 0)
                {
                    var productCount = products.Sum(p => p.Value.Qty);
                    <form class="d-flex">
                        <button class="btn btn-outline-dark" type="submit" value="@Url.Action("Index", "ShoppingCart")">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <span class="badge bg-dark text-white ms-1 rounded-pill">@productCount</span>
                        </button>
                    </form>
                }
                else
                {
                    <form class="d-flex">
                        <button class="btn btn-outline-dark" type="submit" value="@Url.Action("Index","ShoppingCart")">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                        </button>
                    </form>
                }
                @Html.Partial("_LoginPartial")

                <div class="nav-item nav-link">
                    <i class="bi bi-sun-fill "></i>
                    <label class="switch">
                        <input type="checkbox" onclick="toggleTheme('dark')">

                        <span class="slider round"></span>
                    </label>
                    <i class="bi bi-moon-fill"></i>
                </div>
                <script>
                    function myFunction() {
                        var element = document.body;
                        element.classList.toggle(".dark-mode");
                    }
                </script>

            </div>

        </div>
    </nav>
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">StarFront</h1>
                <p class="lead fw-normal text-white-50 mb-0">Shop securely</p>
                <p class="lead fw-normal text-white-50 mb-0">Shop safely</p>
            </div>
        </div>
    </header>
    <!-- Section-->
    <div id="MessageDisplay" class="row">
        <div class="col-md-10 col-md-offset-1" id="MessageContent"></div>
    </div>
    @RenderBody()
    <!-- Footer-->
    <footer class="py-5">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; StarFront @DateTime.Now.Year</p></div>
    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <!--Added jQueryUI-->
    @*<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>*@
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/Scripts/js/scripts.js"></script>
    <!--Added jQueryUI-->
    @*<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>*@
    <!--Added jQuery AJAX CDN-->
    <script src="https://cdn.jsdelivr.net/jquery.ajax.unobtrusive/3.2.4/jquery.unobtrusive-ajax.min.js"></script>



    @RenderSection("scripts", required: false)
</body>
</html>